community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.review_list, name='index'),
    path('create/', views.create_review, name='create'),
    path('<int:review_pk>/', views.review_detail, name='detail'),
    path('<int:review_pk>/update/', views.update_review, name='update'),
    path('<int:review_pk>/delete/', views.delete_review, name='delete'),
]

django_pjt2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
]

community/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=30)
    rank = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(10)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

community/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = '__all__'

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review
from .forms import ReviewForm
from django.views.decorators.http import require_POST

# Create your views here.
def review_list(request):
    reviews = Review.objects.all()[::-1]
    context = {
        'reviews' : reviews
    }
    return render(request, 'community/review_list.html', context)

def create_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form' : form
    }
    return render(request, 'community/form.html', context)

def review_detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    context = {
        'review' : review
    }
    return render(request, 'community/review_detail.html', context)

def update_review(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'community/form.html', context)

@require_POST
def delete_review(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    review.delete()
    return redirect('community:index')

community/templates/community/form.html
{% extends 'base.html' %}

{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
        <h2 class='d-flex justify-content-center my-3 font-weight-bold'>새 글쓰기</h2>
    {% else %}
        <h2 class='d-flex justify-content-center my-3 font-weight-bold'>수정하기</h2>
    {% endif %}

    <!--<form action="" method="POST">-->
    <!--    {% csrf_token %}-->
    <!--    {{ form.as_ul }}-->
    <!--    <input type="submit" value="제출">-->
    <!--</form>-->

    <!--<form action="" method="POST">-->
    <!--    {% csrf_token %}-->
    <!--    {% for field in form %}-->
    <!--        <div class="fieldWrapper">-->
    <!--            {{ field.errors }}-->
    <!--            {{ field.label_tag }} <br> {{ field }}-->
    <!--            {% if field.help_text %}-->
    <!--            <p class="help">{{ field.help_text|safe }}</p>-->
    <!--            {% endif %}-->
    <!--        </div>-->
    <!--    {% endfor %}-->
    <!--    <input type="submit" value="제출">-->
    <!--</form>-->

    <form method="post" novalidate>
      {% csrf_token %}

      {{ form.non_field_errors }}

      {% for hidden_field in form.hidden_fields %}
        {{ hidden_field.errors }}
        {{ hidden_field }}
      {% endfor %}

      <table border="1" class='mx-auto'>
        {% for field in form.visible_fields %}
          <tr>
            <th>{{ field.label_tag }}</th>
            <td>
              {{ field.errors }}
              {{ field }}
              {{ field.help_text }}
            </td>
          </tr>
        {% endfor %}
      </table>

      <button class='btn btn-secondary my-3 d-flex justify-content-center mx-auto' type="submit">Submit</button>
    </form>
{% endblock %}

community/templates/community/review_detail.html
{% extends 'base.html' %}

{% block body %}
<h2 class='d-flex justify-content-center my-3 font-weight-bold'>상세조회</h2>
<p>제목: {{review.title}}</p>
<p>영화제목: {{review.movie_title}}</p>
<p>평점: {{review.rank}}</p>
<p>내용: {{review.content}}</p>
<p>작성시간: {{review.created_at}}</p>
<p>수정시간: {{review.updated_at}}</p>
<div class='d-flex justify-content-center'>
    <a role='botton' class='btn btn-secondary btn-sm' href="{% url 'community:update' review.pk %}">수정</a>
    <form action="{% url 'community:delete' review.pk %}" method="POST" class=d-inline>
        {% csrf_token %}
        <input class='btn btn-secondary btn-sm mx-3' type="submit" value="삭제">
    </form>
    <a role='botton' class='btn btn-secondary btn-sm' href="{% url 'community:index' %}">BACK</a>
</div>
{% endblock %}

community/templates/community/review_list.html
{% extends 'base.html' %}

{% block body %}
    <h2 class='d-flex justify-content-center my-3 font-weight-bold'>게시판</h2>

    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">영화제목</th>
          <th scope="col">평점</th>
        </tr>
      </thead>
      <tbody>
        {% for review in reviews %}
            <tr>
              <th scope="row">{{ review.pk }}번</th>
              <td><a class='text-decoration-none text-secondary' href="{% url 'community:detail' review.pk %}">{{ review.title }}</a></td>
              <td>{{ review.movie_title }}</td>
              <td>{{ review.rank }}</td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <a class='btn btn-secondary vw-10 btn-sm d-flex justify-content-center my-3' href="{% url 'community:create' %}" role='botton'>글쓰기</a>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MOVIE REVIEW</title>
    <!--<link rel="stylesheet" href="{% static 'articles/stylesheets/style.css' %}">-->
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    {% block css %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'community:index' %}">REVIEW</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'community:index' %}">목록</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'community:create' %}">작성</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
</body>
</html>